version: "3.4"


services:
  regolancer:
    container_name: regolancer
    image: regolancer
    build:
      context: ../.
      dockerfile: Dockerfile
    command: [
      "--config=/app/.regolancer/config.toml.sample",
      "--connect=host.docker.internal:10009",
    ]
    volumes:
      - type: bind
        source: ./config_data
        target: /app/.regolancer

    extra_hosts:
      host.docker.internal:host-gateway
 